# -*- coding: utf-8 -*-
"""
Created on Thu Sep 22 09:12:03 2022

@author: Dell
"""
import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go


st.set_page_config(layout='wide') #para ocupar toda la pantalla

st.markdown("<h1 style = 'text-align:center;color:red;'>🏆 CALENDARIOS DEPORTIVOS🥇🏅</h1>", unsafe_allow_html=True)



pd.options.display.float_format = '{:.0f}'.format # organizar los decimales


#--------------------------------------------------------------------------------------------------------------------------
#deputacion de la base

df=pd.read_csv('Calendario_Deportivo.csv',sep=';')
df.drop(['Unnamed: 6','Unnamed: 7','DEPORTE'], axis=1, inplace=True)
df=df.rename(columns={'TIPO':'TIPO DE CALENDARIO'})
df=df.rename(columns={'NOMBRE':'DEPORTE'})
df['DEPORTE']=df['DEPORTE'].replace({'TIRO TODAS':'TIRO DEPORTIVO','TIRO ESCOPETAS':'TIRO DEPORTIVO','TIRO TRAP AUTOMATICO':'TIRO DEPORTIVO','TIRO RIFLES':'TIRO DEPORTIVO','TIRO PISTOLAS':'TIRO DEPORTIVO','TIRO FOSA UNIVERSAL':'TIRO DEPORTIVO','TIRO RIFLES Y PISTOLAS':'TIRO DEPORTIVO','TIRO FOSA OLIMPICA':'TIRO DEPORTIVO','TIRO SPORTING CLAYS':'TIRO DEPORTIVO','TIRO':'TIRO DEPORTIVO','DEPORTES AÃ‰REOS':'DEPORTES AEREOS','TIRO DOBLE TRAP Y FOSA UNIVERSAL':'TIRO DEPORTIVO','TIRO COMPAC SPORTING':'TIRO DEPORTIVO'})
df['TIPO DE CALENDARIO']=df['TIPO DE CALENDARIO'].replace({'CAMPEONATO BOLIVARIANO':'CALENDARIO INTERNACIONAL','CALENDARIO INTERNACINAL':'CALENDARIO INTERNACIONAL','OTRO INTERNACIONAL':'CALENDARIO INTERNACIONAL','NACIONAL':'CALENDARIO NACIONAL','INTERNACIONAL':'CALENDARIO INTERNACIONAL','CAMPEONATO MUNDIAL':'CALENDARIO INTERNACIONAL','CAMPEONATO SURAMERICANO':'CALENDARIO INTERNACIONAL','ACADÃ‰MICO':'ACADEMICO','CAMPEONATO PANAMERICANO':'CALENDARIO INTERNACIONAL','OPEN INTERNACIONAL':'CALENDARIO INTERNACIONAL','CONCENTRACIÃ“N':'CONCENTRACION','GRAN PRIX INTERNACIONAL':'CALENDARIO INTERNACIONAL',' SPORTING CLAYS':'CALENDARIO NACIONAL','SHOWDANCE BAILE DEPORTIVO':'CALENDARIO NACIONAL','SALSA SHOWDANCE':'CALENDARIO NACIONAL','JUEGOS NACIONALES':'CALENDARIO NACIONAL','SUDAMERICANO':'CALENDARIO INTERNACIONAL','CAMPEONATO IBEROAMERICANO':'CALENDARIO INTERNACIONAL','ENCUENTRO NACIONAL DE FOLCLORE DEPORTIVO':'CALENDARIO NACIONAL','CAPACITACIÃ“N':'CAPACITACION','V FORMACION DE JUECES Y ENTRENADORES':'CAPACITACION','CAMPAMENTO':'CALENDARIO NACIONAL','BOGOTA':'CALENDARIO NACIONAL','OPEN DEL CAFÃ‰':'CALENDARIO NACIONAL','OPEN GERMANY':'CALENDARIO INTERNACIONAL','PRECLASIFICATORIO':'CALENDARIO NACIONAL','II CAMPEONATO PANAMERICANO DE BAILE DEPORTIVO':'CALENDARIO INTERNACIONAL','ENTRENADORES':'CAPACITACION','CALENDARIO INTERNACIONAL.':'CALENDARIO INTERNACIONAL','MUNDIAL':'CALENDARIO INTERNACIONAL','RESERVA DEPORTIVA':'CALENDARIO NACIONAL','BRIDGE':'CALENDARIO NACIONAL','CAMPEONATO LATINOAMERICANO':'CALENDARIO INTERNACIONAL','MARATON':'CALENDARIO INTERNACIONAL','CLASIFICATORIO':'CALENDARIO INTERNACIONAL','CAMPEONATO CENTROAMERICANO':'CALENDARIO INTERNACIONAL','TECNICO-METODOLOGICO':'CAPACITACION','EVENTO DEL CICLO OLÃMPICO':'CALENDARIO INTERNACIONAL','COPA MUNDO':'CALENDARIO INTERNACIONAL','CALENDARIO UNICO':'CALENDARIO INTERNACIONAL','COMPETENCIA':'CALENDARIO INTERNACIONAL'})
lista = df[df['TIPO DE CALENDARIO'] == 'POVENZA'].index
lista1 = df[df['TIPO DE CALENDARIO'] == 'WOOPERTTAL'].index
listipo=[lista[0],lista1[0]]
df=df.drop(listipo)
df['PAIS'] = df['PAIS'].replace({'USA':'EEUU','EE.UU':'EEUU','ESPAÃ±A':'ESPAÑA','PERÃŠ':'OTROS','BOYACA':'COLOMBIA','TOLIMA':'COLOMBIA','SANTA MARTA':'COLOMBIA','PAIPA,':'COLOMBIA','POR  DEFINIR':'POR DEFINIR','SIN DEFINIR':'POR DEFINIR','CALI':'COLOMBIA','ESTADOS UNIDOS':'EEUU','BOGOTA':'COLOMBIA','ESPAÃ‘A':'ESPAÑA','VALLE':'COLOMBIA','COLOMBA':'COLOMBIA','META':'COLOMBIA','LIMA':'PERU','SANTIAGO':'CHILE','MÃ‰XICO':'MEXICO','A CONFIRMAR':'POR DEFINIR','MEDELLIN':'COLOMBIA','BOLIVAR':'COLOMBIA','PARIS':'FRANCIA','MONTEMOR':'PORTUGAL','EUROPA':'OTROS','VALLE DEL CAUCA':'COLOMBIA','ANTIOQUIA':'COLOMBIA','ROLDANILLO':'COLOMBIA','CIUDAD DE MEXICO':'MEXICO','MADRID':'ESPAÑA','SANTIAGO DE CHILE':'CHILE','BOGOTÃ D. C.':'COLOMBIA','CÃŠCUTA':'OTROS','COLOMABIA':'COLOMBIA','ARACAJU':'BRASIL','REPUBLICA DE CHINA':'CHINA','IBAGUE (TOLIMA)':'COLOMBIA','CORDOBA':'COLOMBIA','CUBARRAL,':'COLOMBIA','UNITED ARAB EMIRATES':'EMIRATOS ARABAES','POR DEFIIR':'POR DEFINIR','TODAS':'OTROS','CASANARE':'COLOMBIA','BUENOS AIRES':'ARGENTINA','CASTRIES, STA. LUCIA':'SANTA LUCIA','SANTO DOMINGO':'REPUBLICA DOMINICANA','RUSSIA':'RUSIA','REP. DOMINICANA':'REPUBLICA DOMINICANA','REP DOMINICANA':'REPUBLICA DOMINICANA','PAIPA':'COLOMBIA','SANTANDER':'COLOMBIA','BIOLURUSSIA':'BIELURUSIA','GUAYAQUIL, ECUADOR':'ECUADOR','LONATO - ITALIA':'ITALIA','SALVADOR':'EL SALVADOR','BIELURUSSIA':'BIELORUSIA','BOGOTA D.C.':'COLOMBIA','BOG-MIL':'COLOMBIA','EE UU':'EEUU','EUROPA Y ASIA':'OTROS','P. RICO Y CANADÃ':'PUERTO RICO','TOCANCIPA':'COLOMBIA','MALASYA':'MALASIA','SINCELEJO (SUCRE)':'COLOMBIA','BARCELONA':'ESPAÑA','BOY-CAS':'COLOMBIA','EMIRATOS ARABES UNIDOS':'EMIRATOS ARABES','VENDEE':'FRANCIA','MEX-CAN':'MEXICO','PRADO  TOLIMA':'COLOMBIA','HOMSTED MIAMI':'EEUU','ROMA':'ITALIA','CHN-UAE-RUS-GBR-CAN-MEX':'CHINA','CHINA POPULAR':'CHINA','WASQUEHAL':'FRANCIA','NETHERLANDS':'HOLANDA','SWE':'SUIZA','MODENA':'ITALIA','HUI':'COLOMBIA','VARIOS':'OTROS','BELARUS':'BIELORUSIA','SOFIA':'BULGARIA','GUATAPE - ANTIOQUIA':'COLOMBIA','MAGDALENA':'COLOMBIA','CHOCO':'COLOMBIA','CANADÃ':'CANADA','P.D':'POR DEFINIR','FRANCIA  ESPAÃ±A  ITALIA':'FRANCIA','GREAT BRITAIN':'GRAN BRETAÑA','OKLAHOMA CITY':'EEUU','ATL-BOL-COR-MAG':'COLOMBIA','POR ASIGNAR':'POR DEFINIR','GHI':'BOSNIA','SINGAPURE':'SINGAPUR','SUCRE':'COLOMBIA','TUNICIA':'TUNEZ','AZERBAIJAN':'AZERBAYAN','R. DOMINICANA':'REPUBLICA DOMINICANA','NACIONAL':'OTROS','TORONTO':'CANADA','SURREY  BC':'CANADA','GWANGJU':'KOREA','BRASIL-CUBA':'BRASIL','ANT':'COLOMBIA','SAN-NOR':'COLOMBIA','CAU-NAR':'COLOMBIA','GERMANIA':'ALEMANIA','SAN GIL  SANTANDER':'COLOMBIA','UK':'REINO UNIDO','IBAGUE':'COLOMBIA','HCMC-HOCHIMINH CITY':'OTROS','BRASIL - CUBA':'BRASIL','GRAND BRETAÃ±A':'REINO UNIDO','VAL':'OTROS','AMA':'OTROS','UZBEKSITAN':'UZBEKISTAN','CAZHAJTAN':'KAZAJSTAN','BOSNIA AND HERZEGOVINA':'BOSNIA','CARGENTINA':'ARGENTINA','SANCTI ESPÃRITUS':'OTROS','SANCTI ESPÃRITUS':'OTROS','AZERBAYJAN':'AZERBAYAN','ROMANIA':'RUMANIA','CIENAGA':'COLOMBIA','COREO':'KOREA','HAMBURG, ALEMANIA':'ALEMANIA','RACICE':'REPUBLICA CHECA','MEDELLÃN':'COLOMBIA','TERVUREN':'BELGICA','DEPORTIVO':'SIN DEFINIR','GRAND BRETAÃ‘A':'REINO UNIDO','TEMPERE':'FINLANDIA','TORONTO, CANADA':'CANADA','BUCAREST':'RUMANIA','MOSCU, TOKIO':'RUSIA','BERLIN':'ALEMANIA','PEREIRA':'COLOMBIA','GUADALAJARA':'MEXICO','MONTEVELHO,':'PORTUGAL','HAVANA, CUBA':'CUBA','ROMA, ITALIA':'ITALIA','ATHENAS':'GRECIA','SAN JOSE, COSTA RICA':'COSTA RICA','MANAGUA, NICARAGUA':'NICARAGUA','MARRAKECH':'MARRUECOS','SANTA MARTA, COLOMBIA':'COLOMBIA','NEW YORK':'EEUU','GIRARDOT - C/MARCA':'COLOMBIA','ZAMORA, ECUADOR':'ECUADOR','SACATEPEQUEZ, GUATEMALA':'GUATEMALA','COMPETENCIA':'OTROS','CUMANA, VENEZUELA':'VENEZUELA','VARGAS':'ESPAÑA','U-11, U-13':'OTROS','CASTELLETTO - ITALIA':'ITALIA','LA ROMANA, REPÃŠBLICA DOMINICANA':'REPUBLICA DOMINICANA','GUATAPÃ‰':'COLOMBIA','SANTIAGO DE CHILE, CHILE':'CHILE','CARTAGENA':'COLOMBIA','LOULE':'PORTUGAL','MONTREAL':'CANADA','SZOMBATHELY':'HUNGRIA','ALMEIDA':'PORTUGAL','GUAYAQUIL':'ECUADOR','BOGOTÃ':'COLOMBIA','SANTIAGO, REPÃŠBLICA DOMINICANA':'REPUBLICA DOMINICANA','EMIRATOS ÃRABES':'EMIRATOS ARABES','ATLANTICO':'COLOMBIA','ESTADO UNIDOS':'EEUU','KAMPALA':'UGANDA','VILLAVICENCIO - META':'COLOMBIA','MONACO':'FRANCIA','MIAMI - EEUU':'EUU','CAMAGUEY':'CUBA','GEORGETOWN, GUYANA':'GUYANA','PANAMÃ':'PANAMA','AMERICA':'OTROS','CANADÃ':'CANADA','WARLOK':'OTROS','EUROPA / AMERICA':'OTROS','SAN JOSE':'COSTA RICA','SALVADOR - GUATEMALA':'GUATEMALA','PD':'OTROS','NEIVA':'COLOMBIA','U-15, U-21':'OTROS','VALENCIA, VENEZUELA':'VENEZUELA','RISARALDA':'COLOMBIA','TOCANCIPA - COLOMBIA':'COLOMBIA','JAPÃ“N':'JAPON','LA HABANA, CUBA':'CUBA','GUATAVITA':'COLOMBIA','CIUDAD DE GUATEMALA':'GUATEMALA','SOGAMOSO':'COLOMBIA','BELGRADE':'SERBIA','SASSARI':'ITALIA','SZEGUED,':'HUNGRIA','IQUIQUE, CHILE':'CHILE','OSIJEK':'CROACIA','DORMAGEN':'ALEMANIA','KOPER':'ESLOVENIA','CAGUAS, PUERTO RICO':'PUERTO RICO','VILLAVICENCIO':'COLOMBIA','U.S.A.':'EEUU','CAJICA - COLOMBIA':'COLOMBIA','EMIRATOS ARBAES':'EMIRATOS ARABAES','CANADÃ':'CANADA','KAZAJSTAN':'KAZAJISTAN','TOL-CUN':'COLOMBIA','GRAN BRETAÑA':'REINO UNIDO','BHI':'OTROS','EUU':'EEUU','PASTO - NARIÃ‘O':'COLOMBIA','SIN DEFINIR':'POR DEFINIR','PITETI':'OTROS','CAJICA - COLOMBIA':'COLOMBIA','EL SAVADOR':'EL SALVADOR','AZERBAIYÃN':'AZERBAIYAN','OBERHAUSEN':'ALEMANIA','PASTO':'COLOMBIA','RIS-CLA-QUI':'COLOMBIA','AZERBAYAN':'AZERBAIYAN','CANADÃ':'CANADA','EMIRATOS ARABAES':'EMIRATOS ARABES','INDONEDIA':'INDONESIA','CANADÃ\xa0':'CANADA'})
df['PAIS'] = df['PAIS'].str.upper()
df['PAIS']= df['PAIS'].replace({'ESTADOS UNIDOS':'EEUU','ESPAÃ±A':'ESPAÑA','USA':'EEUU'})
lista = df[df['PAIS'] == '3/03/2017 0:00'].index
lista1 = df[df['PAIS'] == '10/05/2017 0:00'].index
lista2 = df[df['PAIS'] == '05/19/2017 12:00:00 AM'].index
lista3 = df[df['PAIS'] == '05/19/2017 12:00:00 AM'].index
lista4 = df[df['PAIS'] == 'MAYORES'].index
lista5 = df[df['PAIS'] == 'JUVENIL'].index
lista6 = df[df['PAIS'] == 'INFANTIL'].index
lista7 = df[df['PAIS'] == '08/18/2017 12:00:00 AM'].index
lista8 = df[df['PAIS'] == '07/20/2017 12:00:00 AM'].index
lista9 = df[df['PAIS'] == 'PRE INFANTIL'].index
lista10 = df[df['PAIS'] == 'U13 U15 U18 MAYORES'].index
lispais=[lista[0],lista1[0],lista2[0],lista3[0],lista4[0],lista4[0],lista5[0],lista6[0],lista7[0],lista8[0],lista9[0],lista10[0]]
df=df.drop(lispais)
df['PAIS']= df['PAIS'].replace({'ESTADOS UNIDOS':'EEUU','ESPAÃ±A':'ESPAÑA','USA':'EEUU','TOLIMA':'COLOMBIA','UNITED ARAB EMIRATES':'EMIRATOS ARABES','VALLE':'COLOMBIA','BOLIVAR':'COLOMBIA','RUSSIA':'RUSIA','REP. DOMINICANA':'REPUBLICA DOMINICANA','IBAGUE (TOLIMA)':'COLOMBIA','CIUDAD DE MEXICO':'MEXICO','CÃŠCUTA':'COLOMBIA','CORDOBA':'COLOMBIA','VALLE DEL CAUCA':'COLOMBIA','META':'COLOMBIA','VAL':'OTROS','POR DEFIIR':'POR DEFINIR','UK':'REINO UNIDO','REPUBLICA DE CHINA':'CHINA','SUCRE':'COLOMBIA','SIN DEFINIR':'POR DEFINIR','SANTIAGO, REPÃŠBLICA DOMINICANA':'REPUBLICA DOMINICANA','SAN-NOR':'COLOMBIA','SINCELEJO (SUCRE)':'COLOMBIA','SINGAPURE':'SINGAPUR','SURREY BC':'CANADA','SWE':'SUECIA','RIS-CLA-QUI':'COLOMBIA','TOL-CUN':'COLOMBIA','TORONTO':'CANADA','A CONFIRMAR':'POR DEFINIR','PARIS':'FRANCIA','BOGOTA D.C.':'COLOMBIA','CHOCO':'COLOMBIA','CHN-UAE-RUS-GBR-CAN-MEX':'VARIOS','CAZHAJTAN':'KAZAJSTAN','CAU-NAR':'COLOMBIA','CARGENTINA':'ARGENTINA','CANADÃ':'CANADA','BRASIL-CUBA':'VARIOS','	BRASIL - CUBA':'VARIOS','BOYACA':'COLOMBIA','BOY-CAS':'COLOMBIA','BOSNIA AND HERZEGOVINA':'BOSNIA','BOG-MIL':'COLOMBIA','EE.UU':'EEUU','BHI':'OTROS','BELARUS':'BIELORUSIA','BARCELONA':'ESPAÑA','AZERBAYAN':'AZERBAIYAN','AZERBAIJAN':'AZERBAIYAN','ATL-BOL-COR-MAG':'COLOMBIA','ANTIOQUIA':'COLOMBIA','ANT':'COLOMBIA','AMA':'COLOMBIA','EMIRATOS ARABES UNIDOS':'EMIRATOS ARABES','OKLAHOMA CITY':'EEUU','IBAGUE':'COLOMBIA','NETHERLANDS':'HOLANDA','MEX-CAN':'VARIOS','MAGDALENA':'COLOMBIA','LA ROMANA, REPÃŠBLICA DOMINICANA':'REPUBLICA DOMINICANA','JUVENIL':'OTROS','INDONEDIA':'INDONESIA','HUI':'COLOMBIA','HCMC-HOCHIMINH CITY':'VIETNAM','GWANGJU':'COREA DEL SUR','GREAT BRITAIN':'REINO UNIDO','GRAND BRETAÃ±A':'REINO UNIDO','GERMANIA':'ALEMANIA','FRANCIA ESPAÃ±A ITALIA':'VARIOS','EUROPA':'OTROS','WASQUEHAL':'FRANCIA'})
df['PAIS']= df['PAIS'].replace({'PERÃŠ':'OTROS','KOREA':'COREA','AZERBAIYAN':'AZERBAIJAN','VENDEE':'OTROS','SURREY BC':'CANADA','SANTO DOMINGO':'REPUBLICA DOMINICANA','BRASIL - CUBA':'VARIOS','CANADÃ\xa0':'CANADA','FRANCIA  ESPAÃ±A  ITALIA':'VARIOS','R. DOMINICANA':'REPUBLICA DOMINICANA'})
df['LUGAR'] = df['LUGAR'].replace({'CARACAS Y VALENCIA':'CARACAS-VALENCIA','LONG ISLAND  NY':'LONG ISLAND','TAME (ARAUCA)':'TAME','ACACIAS (META)':'ACACIAS','CALI Â€“ VALLE DEL CAUCA':'CALI','OROCUE (CASANARE)':'OROCUE','CUENCA / ECUADOR':'CUENCA','SANTA ROSALIA (VICHADA)':'SANTA ROSALIA','13 - 15 FUSAGASUGA':'FUSAGASUGA','MEX-CAN':'MEXICO-CANADA','GUARNE (ANT)':'GUARNE','CHN-UAE-RUS-GBR-CAN-MEX':'CHINA-EMIRATOS ARABES-REINO UNIDO-CANADA-MEXICO','DENVER CO':'DENVER','BOGOTA Y BONSA':'BOGOTA-BONSA','AGUAZUL (CASANARE)':'AGUAZUL','SAO_PAULO':'SAO PAULO','GREEN BAY  WISCONSIN':'GREEN BAY','TRINIDAD(CASANARE)':'TRINIDAD','BOGOTA- BONZA':'BOGOTA-BONZA','LA CEJA - ANT.':'LA CEJA','RIONEGRO (ANT)':'RIONEGRO','VIRTUAL/ FECODAZ':'VIRTUAL-FECODAZ','TORONTO (CAN)':'TORONTO','TORONTO/CANADA':'TORONTO','SAN DIEGO  CA':'SAN DIEGO','IBAGUE - TOLIMA':'IBAGUE','BARRANQUILLA-COLOMBIA':'BARRANQUILLA','PUN TA CANA':'PUNTA CANA','PEREIRA - RISARALDA':'PEREIRA','BRIENZA_AXALP':'BRIENZA AXALP','BOGOTA/CUNDINAM':'BOGOTA','MONTERREY (CASANARE)':'MONTERREY','MARINIÃ‘Ã‘A':'MARINILLA','SAN GIL - SAN':'SAN GIL','RIO - HABANA':'RIO-HABANA','GUATAPE ANTIOQUIA':'GUATAPE','SAN ANTONIO (TEXAS)':'SAN ANTONIO','PORE (CASANARE)':'PORE','LIBANO - TOLIMA':'LIBANO','QUIBDO - CHOCO':'QUIBDO','BOJACA CUNDINAMARCA':'BOJACA','PALESTINA - CALDAS':'PALESTINA','BOGOTA - CALI':'BOGOTA-CALI','RIONEGRO - ANT.':'RIONEGRO','PALESTINA - CALDAS':'PALESTINA','YOPAL (CASANARE)':'YOPAL','BOGOTÃ\x81  (CLUB LOS ARRAYANES':'BOGOTA','CARTAGENA. BOLÃ\x8dVAR':'CARTAGENA','MIAMI, FL':'MIAMI','MIAMI, FLORIDA':'MIAMI','OCALA - FLORIDA':'OCALA-FLORIDA','SÃƑO JOSÃ‰ DOS CAMPOS':'SAN JOSE DOS CAMPOS','BOGOTÃ\x81  (CLUB HATOGRANDE)':'BOGOTA','SAN JUAN Y GATINEAU':'SAN JUAN-GATINEAU','EUROPA -ASIA':'EUROPA-ASIA','FRISCO - TEXAS':'FRISCO-TEXAS','PALM BEACH - FLORIDA':'PALM BEACH','LIGNANO - SABBIADORO':'LIGNANO-SABBIADORO','MANIZALES, CALDAS':'MANIZALES','CARTAGENA-BOLIVAR':'CARTAGENA','GUATAPÃ‰':'GUATAPE','CARTAGENA-BOLIVAR':'CARTAGENA','STO DOMINGO':'SANTO DOMINGO','BOGOTÃ\x81, CUNDINAMARCA':'BOGOTA','CULIACAN SINALOA':'CULIACAN','PEREIRA-RISARALDA':'PEREIRA','SAN JUAN PTO RICO':'SAN JUAN','COTA CUNDINAMARCA PUEBLO VIEJO':'COTA-PUEBLO VIEJO','FECODAZ/BOGOTÃ\x81':'FECODAZ-BOGOTA','VILLA DE LEYVA CUND':'VILLA DE LEYVA','MISSANO Y TRIETE':'MISSANO-TRIETE','ASIAGO - ROANA':'ASIAGO-ROANA','BARRANQUILA-ATLANTICO':'BARRANQUILA','BOGOTÃ\x81, MEDELLIN, CALI':'BOGOTA-MEDELLIN-CALI','BAKÃŠ':'BAKAS','NEIVA Y TUNJA':'NEIVA-TUNJA','IBAGUÃ‰, TOLIMA':'IBAGUE','BUCARAMANGA-SANTANDER':'BUCARAMANGA','B/MANGA':'BUCARAMANGA','MEDELLÃ\x8dN, ANTIOQUIA':'MEDELLIN','LUBBOCK, TEXAS':'LUBBOCK','RESTREPO - VAL.':'RESTREPO','RÃ\x8dO DE JANEIRO':'RIO DE JANEIRO','RIO NEGRO ANT.':'RIO NEGRO','UBATE CUND':'UBATE','POPAYÃ\x81N':'POPAYAN','CUND':'CUNDINAMARCA','TAOYUAN, CHINESE TAIPEI':'TAOYUAN-TAIPEI','ATLÃ\x81NTICO':'ATLANTICO','3 ZONAS DEL PAIS':'COLOMBIA','BOGOTA BACATA':'BOGOTA-BACATA','SAN ANDRES ISLAS':'SAN ANDRES','DUITAMA BONZA':'DUITAMA-BONZA','PUERTO TRIUNFO  A CARTAGENA':'PUERTO TRIUNFO-CARTAGENA','FRANCIA/ARGENTINA /BRASIL/CUBA/ESPAÃ‘A/ HUNGRIA/ITALIA/POLONIA':'FRANCIA-ARGENTINA-BRASIL-CUBA-ESPAÑA-HUNGRIA-ITALIA-POLONIA','FRANCIA/ITALIA/ESPAÃ‘A/ALEMANIA':'FRANCIA-ITALIA-ESPAÑA-ALEMANIA','8 CIUDADES':'VARIOS','SUBACHOQUE CUND':'SUBACHOQUE','XIÂ€™AN':'OTROS','ANAPOLIS, MAYLAND':'ANAPOLIS-MAYLAND','P/D':'POR DEFINIR','BUCARMANGA. SANTANDER':'BUCARMANGA','KAZÃ\x81N':'OTROS','BARRANQUILLA - CARTAGENA':'BARRANQUILLA-CARTAGENA','TBA':'OTROS','SIN DEFINIR':'POR DEFINIR','CAVASA - CALI':'CAVASA-CALI','LAGUNA SECA - CHIA':'LAGUNA SECA-CHIA','CAJICA LA HA':'CAJICA','CALI CCC':'CALI','BOGOTA, MANIZALEZ, MEDELLIN, BARRANQUILLA, CALI':'BOGOTA-MANIZALEZ-MEDELLIN-BARRANQUILLA-CALI','PRADO - TOLIMA':'PRADO','MEDELLIN-ANTIOQUIA':'MEDELLIN','ARJONA-BOLIVAR':'ARJONA','B/QUILLA':'BARRANQUILLA','BOGOTA EEEE':'BOGOTA','BOGOTA RANCHO':'BOGOTA','POR ASIGNAR':'POR DEFINIR','DESCENTRALIZADO':'VARIOS','CIUDAD DE PANAMÃ\x81':'CIUDAD DE PANAMA','RÃ\x8dO GRANDE':'OTROS','VALLE DE BRAVO - MEXICO':'VALLE DE BRAVO','VIÃ‘A DEL MAR':'VIA DEL MAR','SANTIAGO, REPÃŠBLICA DOMINICANA':'SANTIAGO-REPUBLICA DOMINICANA','AUTODROMO DE TOCANCIPA':'TOCANCIPA','JERICO - ANTIOQUIA':'JERICO','VARIAS CIUDADES':'VARIOS','BARRANQUILLA - ATLANTICO':'BARRANQUILLA','EUROPA':'VARIOS','GEORGETOWN, GUYANA':'GEORGETOWN','PUERTO LOPEZ ( META)':'PUERTO LOPEZ','RUITOQUE - SANTANDER':'RUITOQUE','QUERÃ‰TARO':'QUERETARO','FLANDES -  TOLIMA':'FLANDES','COEUR DE SAVOIE - FRANCIA':'COEUR DE SAVOIE','LIGA DE SQUASH DE VALLE':'VALLE DEL CAUCA','BOGOTA, CALI, MEDELLIN':'BOGOTA-CALI-MEDELLIN','IQUIQUE, CHILE':'IQUIQUE','HUNGRÃ\x8dA':'HUNGRIA','A DEFINIR':'POR DEFINIR','BOGOTÃ\x81 D. C.':'BOGOTA','A CONFIRMAR':'POR DEFINIR','IBAGUÃ‰':'IBAGUE','LA HABANA, CUBA':'LA HABANA','LIGA DE SQUASH DE ANTIOQUIA-COUNTRY EJECUTIVOS':'ANTIOQUIA','IBAGUE TOLIMA':'IBAGUE','CARTAGENA DE INDIAS':'CARTAGENA','PROVIDENCIA ISLAS':'PROVIDENCIA','APIA - RISARALDA':'APIA','CALI/CUCUTA/PEREIRA/MEDELLIN/BOGOTA/BARRANQUILLA/RIOACHA':'CALI-CUCUTA-PEREIRA-MEDELLIN-BOGOTA-BARRANQUILLA-RIOACHA','LAGO CALIMA - VALLE':'LAGO CALIMA','MOLVENO - ITALIA':'MOLVENO','LIGA DE SQUASH DE META':'META','VALENCIA, VENEZUELA':'VALENCIA','IBAGUÃ‰ TOLIMA':'IBAGUE','COSTA NORTE, MEDELLIN,CALI':'COSTA NORTE-MEDELLIN-CALI','ESPAÃ‘A':'ESPAÑA','RUSIA, ASIA':'RUSIA-ASIA','COSTA NORTE, ZONA URABA. MEDELLIN, CALI':'COSTA NORTE-URABA-MEDELLIN-CALI','ASUNCIÃ“N':'ASUNCION','PALM BEACH, FLORIDA':'PALM BEACH','AGUAZUL - CASANARE':'AGUAZUL-CASANARE','TORONTO, CANADA':'TORONTO','LIGA DE SQUASH DE ANTIOQUIA- RODEO':'EL RODEO','PERÃŠ':'OTROS','RIONEGRO ANT':'RIONEGRO','CARTAGO - VALLE':'CARTAGO','DISENTIS - SUIZA':'DISENTIS','PIEDECHINCHE - VALLE':'PIEDECHINCHE','BÃ‰LGICA':'BELGICA','CALI VALLE':'CALI','BERLÃ\x8dN':'BERLIN','ZELL AM SE - AUSTRIA':'ZELL AM SE','REP.CHECA':'REPUBLICA CHECA','ANNECY - FRANCIA':'ANNECY','LIGA DE SQUASH DE BOLIVAR':'BOLIVAR','HAVANA, CUBA':'LA HAVANA','ANDRADAS - BRASIL':'ANDRADAS','PAIPA - BOYACA':'PAIPA','PAIPA - BOYACA':'PAIPA','LIGA DE SQUASH DE SANTANDER':'SANTANDER','MEDELLIN ANTIOQUIA':'MEDELLIN', 'SANTIAGO DE CHILE, CHILE': 'SANTIAGO DE CHILE','GUAYAQUIL, ECUADOR':'GUAYAQUIL','MEDELLIN - ANTIOQUIA':'MEDELLIN','LA ROMANA, REPÃŠBLICA DOMINICANA':'LA ROMANA','PILAR - BUENOS AIRES':'PILAR-BUENOS AIRES','PRADO TOLIMA':'PRADO','VILLAVICENCIO META':'VILLAVICENCIO','CIUDAD DE MÃ‰XICO':'CIUDAD DE MEXICO','CIUDAD DE MÃ‰XICO,':'CIUDAD DE MEXICO','SAN JOSE, COSTA RICA':'SAN JOSE','CUMANA, VENEZUELA':'CUMANA','CALI/BOGOTA':'CALI-BOGOTA','BOGOTA/NORTE DE SANTANDER/SANTANDER/MEDELLIN/CALI/PEREIRA/BARRANQUILLA':'BOGOTA-NORTE DE SANTANDER-SANTANDER-MEDELLIN-CALI-PEREIRA-BARRANQUILLA','GACHALA - CUNDINAMARCA':'GACHALA','EE.UU.':'EEUU','BOTOTILLO - ECUADOR':'BOTOTILLO','SACATEPEQUEZ, GUATEMALA':'SACATEPEQUEZ','COSTA NORTE, URABA, MEDELLIN, CALI':'COSTA NORTE-URABA-MEDELLIN-CALI','ANSERMA - VALLE':'ANSERMA','CASTRIES, STA. LUCIA':'CASTRIES','ZAMORA, ECUADOR':'ZAMORA','MACANAL - BOYACA':'MACANAL','BOGOTÃ\x81':'BOGOTA','USA':'EEUU','MONTERÃ\x8dA':'MONTERIA','SANTA MARTHA':'SANTA MARTA','PACHAVITA - BOYACA':'PACHAVITA','SANTA MARTA, COLOMBIA':'SANTA MARTA','LIGA DE  SQUASH DE CUNDINAMARCA':'CUNDINAMARCA','MANAGUA, NICARAGUA':'MANAGUA','LIGA DE SQUASH DE BOGOTÃ€- NOGAL':'BOGOTA','VILLAVICENCIO - META':'VILLAVICENCIO','BELLO HORIZINTE -VALLE':'BELLO HORIZINTE','CALI/CUCUTA/PEREIRA/MEDELLIN/BOGOTA/BARRANQUILLA/RIOACHA/SANTANDER/':'CALI-CUCUTA-PEREIRA-MEDELLIN-BOGOTA-BARRANQUILLA-RIOACHA-SANTANDER','ROLDANILLO - VALLE':'ROLDANILLO','CORAL GABLES, FL':'CORAL GABLES','LIMA -PERU':'LIMA','PILAR-ARGENTINA':'PILAR','BOGOTÃ\x81 - COLOMBIA':'BOGOTA','TAOYUAN, CHINESE':'TAOYUAN','MEDELLÃ\x8dN':'MEDELLIN','MALAGA NORTE S/DER':'MALAGA','CHIA - CMARCA':'CHIA','TOMINÃ‰ - MUÃ‘A':'OTROS','CUENCA -ECUADOR':'CUENCA','SPOKANE - USA':'SPOKANE','NEUSA, CUNDINAMARCA':'NEUSA','EGYPTO/ CAIRO':'CAIRO','COLOMBIA/ PENDIENTE':'COLOMBIA','VILLETA CUNDINAMARCA':'VILLETA','BARCELONA ESPAÃ‘A':'BARCELONA','SAN DIEGO CA USA':'SAN DIEGO','WRIGHTSVILLE BEACH/NC / USA':'WRIGHTSVILLE BEACH','NARIÃ‘O':'NARIÑO','MONTERÃ\x8dA CORDOBA':'MONTERIA','BUENOS AIRES, ARGENTINA':'BUENOS AIRES','CALIMA - CLUB NÃ\x81UTICO DEL PACÃ\x8dFICO':'CALIMA','BUENOS AIRES (ARG)':'BUENOS AIRES','DOHA - QATAR':'DOHA','BOGOTA   COL':'BOGOTA','BUENOS AIRES - ARGENTINA':'BUENOS AIRES','LIGA CUNDINAMARCA':'CUNDINAMARCA','RIO MAGDALENA':'MAGDALENA','SOGAMOSO - BOYACÃ\x81':'SOGAMOSO','CIRCUITO EUROPEO':'OTROS','COLOMBIA/ CUNDINAMARCA':'CUNDINAMARCA','PALMIRA - VALLE - COLOMBIA':'PALMIRA','GUATAPÃ‰- ANTIOQUIA':'GUATAPE','MADRID - ESPAÃ‘A':'MADRID','ST. PETERSBURG - RUSSIA':'SAN PETERSBURGO','TOCAIMA CUNDINAMARCA':'TOCAIMA','OBERHAUSEN (NORTHRHINE-WESTFALIA) - GER':'OBERHAUSEN','BOGOTA  ARRAYANES':'BOGOTA','X DEFINIR':'POR DEFINIR','MONTEVIDEO- URUGUAY':'MONTEVIDEO','SANTA MARTA MAGDALENA':'SANTA MARTA','VALLLE':'VALLE','BOGOTÃ\x81 D.C.':'BOGOTA','BOGOTÃ¡':'BOGOTA','SANTA MARTA-MAGDALENA':'SANTA MARTA','TOMINÃ‰ - CNP':'OTROS','GIRARDOT CUNDINAMARCA':'GIRARDOT','TUNJA (BOYACA) COLOMBIA':'TUNJA','PUCÃ“N CHILE':'PUCANA','MIAMI- ESTADOS UNIDOS':'MIAMI','BOGOTA  (CLUB LOS LAGARTOS)':'BOGOTA','KAOSHIUNG (TAIPEI)':'KAOSHIUNG','SAN ANTONIO  TX':'SAN ANTONIO','BARRANQUILLA- CALI':'BARRANQUILLA-CALI','HANGZHOU-CHN':'HANGZHOU','CÃŠCUTA':'CUCUTA','OKALA FLA.':'OKALA','OVERLAND PARK KS':'OVERLAND PARK','PD':'OTROS','SACATEPÃ‰QUEZ':'SACATEPEQUEZ','BAKÃŠ':'OTROS','LA ROMANA, REPÃŠBLICA DOMINICANA':'LA ROMANA','HAMBURG, ALEMANIA':'HAMBURG','OBERHAUSEN (NORTHRHINE-WESTFALIA) - GER':'OBERHAUSEN','COLOMBIA/ CUNDINAMARCA':'CUNDINAMARCA','NEIVA HUILA':'NEIVA','CHINA.':'CHINA','EGYPTO/ CAIRO':'CAIRO','NEUSA, CUNDINAMARCA':'NEUSA','FLORIDABLANCA , SANTANDER':'FLORIDABLANCA','SANTIAGO, REPÃŠBLICA DOMINICANA':'SANTIAGO','CAGUAS, PUERTO RICO':'CAGUAS','PEDAVENA - ITALIA':'PEDAVENA','SAN ANTONIO - TEXAS':'SAN ANTONIO','CALI - VALLE DEL CAUCA':'CALI','SAN ANDRE ISLAS':'SAN ANDRES','CATALUÃ‘A':'CATALUÑA','BUFFALO  NY':'BUFFALO','LIGA DE SQUASH DE BOGOTA':'BOGOTA','PINEHURST  CAROLINA DEL NORTE':'PINEHURST-CAROLINA DEL NORTE','NEIVA - HUILA':'NEIVA','WARREN NJ':'WARREN','ZIOLKOWSK Y PYTLASINSKI':'ZIOLKOWSK-PYTLASINSKI','PALM BEACH GARDENS  FL':'PALM BEACH GARDENS','DURBANVILLE  CAPE TOWN':'DURBANVILLE-CAPE TOWN','LOMBARD ILL':'LOMBARD','PORTLAND OR':'PORTLAND','LA VIRGINIA RISARALDA':'LA VIRGINIA-RISARALDA','SAO_PAULO':'SAO PAULO','LONG BEACH CA':'LONG BEACH','CALI Â€“ VALLE DEL CAUCA':'CALI','OVERLAND PARKS KS':'OVERLAND','MINNEAPOLIS  MN':'MINNEAPOLIS','SAN DIEGO CA':'SAN DIEGO','SIOUX FALL SD':'SIOUX FALL','STOCKTON  CA':'STOCKTON','CINCINATTI OH':'CINCINATTI','DAVISON MI':'DAVISON','FRANCIA  ESPAÃ‘A  ITALIA':'FRANCIA-ESPAÑA-ITALIA','WELLINGTON FLA.':'WELLINGTON','PUERTO LOPEZ META':'PUERTO LOPEZ','PERÃŠ':'OTROS','COLOMBIA/ PENDIENTE':'OTROS','SEATTLE WA':'SEATTLE','SÃƑO JOSÃ‰ DOS CAMPOS':'SAN JOSE DOS CAMPOS','PEREIRA - RDA':'PEREIRA','BOGOTÃ¡':'BOGOTA','EL SALVADOR':'SAN SALVADOR','CÃŠCUTA':'CUCUTA','P.D':'POR DEFINIR','CORAL GABLES  FL':'CORAL GABLES','MIAMI  FL':'MIAMI','BARBOSA - SANTANDER':'BARBOSA','TARIJA,':'TARIJA','SARASOTA FL':'SARASOTA','MILLBROOK ONT':'MILLBROOK','ELOY  ARIZONA  USA':'ELOY','TORONTO  CANADA':'TORONTO','SANTA CRUZ DE LA SIERRA':'SANTA CRUZ','FOUNTAIN VALLEY CA':'FOUNTAIN VALLEY','WELLINGTON FLA':'WELLINGTON','ARLINGTON VA':'ARLINGTON','FULLERTON  CA':'FULLERTON','RESEDA CA':'RESEDA','QUITO- GUAYAQUIL':'QUITO-GUAYAQUIL','MEXICO  DF':'MEXICO','FUNZA CUND SAN ANDRES':'FUNZA-SAN ANDRES','CIUDAD DE MEXICO':'MEXICO','POR CONFIRMAR':'POR DEFINIR','STA MARTA':'SANTA MARTA'})
df['LUGAR'] = df['LUGAR'].str.upper()
lista = df[df['LUGAR'] == 'DEL 26 AL 30 /01/2015'].index
lista1 = df[df['LUGAR'] == 'NACIONAL'].index
lista2 = df[df['LUGAR'] == '42305'].index
lista3 = df[df['LUGAR'] == '42320'].index
lista4 = df[df['LUGAR'] == 'REGIONAL'].index
lista5 = df[df['LUGAR'] == 'ESTADOS UNIDOS'].index
lista6 = df[df['LUGAR'] == 'FEBRERO 17 AL 19'].index
lista7 = df[df['LUGAR'] == '27 JUNIO A 2 DE JULIO'].index
lista8 = df[df['LUGAR'] == 'ABRIL 29 Y 30'].index
lista9 = df[df['LUGAR'] == 'FEBRERO 17 AL 19'].index
lista10 = df[df['LUGAR'] == '27 JUNIO A 2 DE JULIO'].index
lista11 = df[df['LUGAR'] == 'JUNIO 8 A 11'].index
lista12 = df[df['LUGAR'] == 'JUNIO'].index
lista13 = df[df['LUGAR'] == '8/05/2017 0:00'].index
lista14 = df[df['LUGAR'] == 'AGOSTO 5 Y 6'].index
lista15 = df[df['LUGAR'] == 'SEPTIEMBRE'].index
lista16 = df[df['LUGAR'] == 'DICIEMBRE'].index
lista17 = df[df['LUGAR'] == 'OCTUBRE'].index
lista18 = df[df['LUGAR'] == 'NOVIEMBRE'].index
lista19 = df[df['LUGAR'] == 'NOVIEMBRE 5 Y6'].index
lista20 = df[df['LUGAR'] == 'MARZO 19 Y 20'].index 
lista21 = df[df['LUGAR'] == 'JULIO'].index 
lislugar=[lista[0],lista1[0],lista2[0],lista3[0],lista4[0],lista4[0],lista5[0],lista6[0],lista7[0],lista8[0],lista9[0],lista10[0],lista11[0],lista12[0],lista13[0],lista14[0],lista15[0],lista16[0],lista17[0],lista18[0],lista19[0],lista20[0],lista21[0]]
df=df.drop(lislugar)
df=df.reset_index()
d_f=df.groupby(['TIPO DE CALENDARIO'])[['index']].sum().reset_index()
df['PAIS']= df['PAIS'].replace({'MAYORES':'OTROS','COLOMBA':'COLOMBIA','UZBEKSITAN':'UZBEKISTAN','SURREY BC':'CANADA'})
#--------------------------------------------------------------------------------------------------------------------------
import datetime
from datetime import datetime
df['FECHA']= pd.to_datetime(df['FECHA'], dayfirst=True, errors='coerce')# Convertir la fecha en el formato correcto
#Para cambiar el formato de la fecha tuve que agg dayfirst=True y errors='coerce'
type(df['FECHA'][4])
#--------------------------------------------------------------------------------------------------------------------------
años=df.groupby(['FECHA'])[['index']].count().reset_index()
años['FECHA']=años['FECHA'].dt.year
años=años.groupby(['FECHA'])[['index']].sum().reset_index()
st.markdown("<h4 style = 'text-align:center;color:gray;'>NUMERO DE CALENDARIOS DEPORTIVOS DONDE PARTICIPAN COLOMBIANOS📆📅  </h4>", unsafe_allow_html=True)
c1,c2,c3,c4,c5 = st.columns([0.3,1,1,1, 0.35])
#eventos del año 2015
a1=años.loc[0,'index']
#eventos del año 2016
a2=años.loc[1,'index']
#eventos del año 2015
a3=años.loc[2,'index']
#eventos del año 2015
a4=años.loc[3,'index']

c2.markdown("<h4 style = 'text-align:left;color:white;'> 2015</h4>", unsafe_allow_html=True)
c2.text(a1)

c3.markdown("<h4 style = 'text-align:left;color:white;'> 2016</h4>", unsafe_allow_html=True)
c3.text(a2)

c4.markdown("<h4 style = 'text-align:left;color:white;'> 2017</h4>", unsafe_allow_html=True)
c4.text(a3)

c5.markdown("<h4 style = 'text-align:left;color:white;'> 2018</h4>", unsafe_allow_html=True)
c5.text(a4)

cf=df.copy()
cf=cf.groupby(['FECHA'])[['index']].count().sort_values('index', ascending = False).reset_index()
# crear un dataframe con todas las fechas
dff= pd.DataFrame(pd.date_range(start=df['FECHA'].min(), end=df['FECHA'].max())).rename(columns ={0:'FECHA'})
df2= pd.merge(dff, cf, on ='FECHA', how ='left')
# generar base
df2.iloc[:,1:]= df2.rolling(window=3).mean().fillna(0)
c1,c2,c3 = st.columns([0.2,5, 0.2])
fig = px.line(df2, x='FECHA', y='index')

# agregar detalles
fig.update_layout(
    xaxis_title = 'Fecha',
    yaxis_title = 'Cantidad de calendarios',
    template = 'simple_white',
    title_x = 0.5,
    width=1150, height=500,
    paper_bgcolor='rgba(0,0,0,0)',
    plot_bgcolor='rgba(0,0,0,0)')
fig.update_traces(line_color='red')
c2.plotly_chart(fig)


#--------------------------------------------------------------------------------------------------------------------------

st.markdown("<h2 style = 'text-align:center;color:gray;'>PARTICIPACION DE COLOMBIA EN EL DEPORTE MUNDIAL 🏁🚩🎌</h2>", unsafe_allow_html=True)
c1,c2,c3,c4,c5 = st.columns([0.1,3,0.1,3, 0.1])
df['NACIONAL/INTERNACIONAL']=0
df['NACIONAL/INTERNACIONAL']=df['PAIS'].apply(lambda x: "NACIONAL" if x =='COLOMBIA' else "INTERNACIONAL")
ni=df.groupby(['NACIONAL/INTERNACIONAL'])[['index']].count().reset_index()

st.markdown("<h4 style = 'text-align:center;color:gray;'>PARTICIPACIONES DE COLOMBIA EN EL MUNDO 🏁🚩🎌</h4>", unsafe_allow_html=True)
fig = px.pie(ni , values = 'index', names = 'NACIONAL/INTERNACIONAL',color='NACIONAL/INTERNACIONAL',color_discrete_map={'NACIONAL':'red',
                                 'INTERNACIONAL':'dimgray'})
# agregar detalles a la gráfica
fig.update_layout(
    template = 'simple_white',
    legend_title = 'LOCACION:',
    title_x = 0.5,    width=550, height=550)

fig.update_layout(legend=dict(
    orientation="h",
    yanchor="bottom",
    y=-0.06,
    xanchor="right",
    x=0.9))
c2.markdown("<h4 style = 'text-align:center;color:gray;'>PROPORCION DE CALENDARIOS NACIONALES E INTERNACIONALES</h4>", unsafe_allow_html=True)
c2.plotly_chart(fig)

ff=df.groupby(['PAIS'])[['FECHA']].count().sort_values('FECHA', ascending = False).reset_index()
ff['nc'] = ff['PAIS'].str.capitalize()
ff=ff.head(34)
ff['nc']=ff['nc'].replace({'Colombia':'COL','Eeuu':'USA','Brasil':'BRA','Mexico':'MEX','Argentina':'ARG','Peru':'PER','Canada':'CAN','Chile':'CHL','Francia':'FRA','Ecuador':'ECU','Italia':'ITA','España':'ESP','Bolivia':'BOL','Rusia':'RUS','Alemania':'DEU','Venezuela':'VEN','Paraguay':'PRY','China':'CHN','Polonia':'POL','Guatemala':'GTM','Cuba':'CUB','Uruguay':'URY','Portugal':'PRT','Republica dominicana':'DOM','Japon':'JPN','Turquia':'TUR','Puerto rico':'PRI','Panama':'PAN','El salvador':'SLV','Costa rica':'CRI','Grecia':'GRC','Hungria':'HUN'})
l1 = ff[ff['nc'] == 'Otros'].index
#l2 = ff[ff['nc'] == 'Mayores'].index 
l3 = ff[ff['nc'] == 'Por definir'].index
li=[l1[0],l3[0]]  
l4 = ff[ff['nc'] == 'COL'].index
l=l4[0]
ff=ff.drop(li)
ff=ff.drop(l) 
ff=ff.rename(columns={'FECHA':'PARTICIPACIONES'})

fs=ff.head(10)
# crear gráfica
fig = px.bar(fs, x='PAIS', y='PARTICIPACIONES',color='PAIS',color_discrete_map={'EEUU':'red',
                                 'BRASIL':'lawngreen','MEXICO':'darkgreen','ARGENTINA':'mediumturquoise','PERU':'firebrick','CANADA':'white','CHILE':'blue','FRANCIA':'midnightblue','ECUADOR':'yellow','ITALIA':'lime'})

# agregar detalles a la gráfica
fig.update_layout(
    xaxis_title = 'PAIS',
    yaxis_title = 'PARTICIPACIONES',
    
    template = 'simple_white',
    title_x = 0.5,    width=600, height=525,
    paper_bgcolor='rgba(0,0,0,0)',
    plot_bgcolor='rgba(0,0,0,0)')
fig.update_layout(showlegend=False)
                
c4.markdown("<h4 style = 'text-align:center;color:gray;'>TOP DE PAISES EN DONDE MAS REPRESNTAN LOS COLOMBIANOS</h4>", unsafe_allow_html=True)
c4.plotly_chart(fig)

ff=df.groupby(['PAIS'])[['FECHA']].count().sort_values('FECHA', ascending = False).reset_index()
ff['nc'] = ff['PAIS'].str.capitalize()
ff=ff.head(34)
ff['nc']=ff['nc'].replace({'Colombia':'COL','Eeuu':'USA','Brasil':'BRA','Mexico':'MEX','Argentina':'ARG','Peru':'PER','Canada':'CAN','Chile':'CHL','Francia':'FRA','Ecuador':'ECU','Italia':'ITA','España':'ESP','Bolivia':'BOL','Rusia':'RUS','Alemania':'DEU','Venezuela':'VEN','Paraguay':'PRY','China':'CHN','Polonia':'POL','Guatemala':'GTM','Cuba':'CUB','Uruguay':'URY','Portugal':'PRT','Republica dominicana':'DOM','Japon':'JPN','Turquia':'TUR','Puerto rico':'PRI','Panama':'PAN','El salvador':'SLV','Costa rica':'CRI','Grecia':'GRC','Hungria':'HUN'})
l1 = ff[ff['nc'] == 'Otros'].index
#l2 = ff[ff['nc'] == 'Mayores'].index 
l3 = ff[ff['nc'] == 'Por definir'].index
li=[l1[0],l3[0]]  
l4 = ff[ff['nc'] == 'COL'].index
l=l4[0]
ff=ff.drop(li)
ff=ff.drop(l) 
ff=ff.rename(columns={'FECHA':'PARTICIPACIONES'})

c1,c2,c3= st.columns([0.2, 5, 0.2])
    
fig = px.scatter_geo(ff, locations="nc", color="PAIS", hover_name="PAIS", size="PARTICIPACIONES",
                      template = 'plotly_dark',
                      projection="natural earth",
                      width=1100, height=600
                  )
fig.update_layout(showlegend=False) 
c2.plotly_chart(fig)


#--------------------------------------------------------------------------------------------------------------------------
df['FECHA']=df['FECHA'].dt.strftime('%m-%d-%Y')
df=df.rename(columns={'TIPO DE CALENDARIO':'TIPO_DE_CALENDARIO'})
cpp=df.groupby(['FECHA','PAIS','TIPO_DE_CALENDARIO','DEPORTE'])[['index']].count().sort_values('index', ascending = False).reset_index().rename(columns={'index':'NUMERO_DE_EVENTOS'})
if st.checkbox('Obtener datos por fecha,pais, tipo de calendario y deporte', False):
    
    
    fig = go.Figure(data=[go.Table(
        header=dict(values=list(cpp.columns),
        fill_color='red',
        line_color='gray'),
        
       cells=dict(values=[cpp.FECHA, cpp.PAIS, cpp.TIPO_DE_CALENDARIO, cpp.DEPORTE,cpp.NUMERO_DE_EVENTOS],fill_color='black',line_color='lightgrey'))
    ])
    
    fig.update_layout(width=1500, height=600)
    st.plotly_chart(fig)

#--------------------------------------------------------------------------------------------------------------------------
from PIL import Image

background = Image.open('banderas.jpg')
col1, col2, col3 = st.columns([0.2, 5, 0.2])
col2.image(background, width=1138)
#--------------------------------------------------------------------------------------------------------------------------
c1, c2= st.columns((1,1))


fig = px.pie(d_f , values = 'index', names = 'TIPO DE CALENDARIO',color='TIPO DE CALENDARIO',color_discrete_map={'DEPORTIVO':'red','CALENDARIO NACIONAL':'silver','CALENDARIO INTERNACIONAL':'maroon','ACADEMICO':'orangered','CONCENTRACION':'sienna','ADMINISTRATIVO':'grey','CAPACITACION':'whitesmoke'})

# agregar detalles a la gráfica
fig.update_layout(
    template = 'simple_white',
    legend_title = '<b>Tipos de calendarios: <b>',
    title_x = 0.4, 
    width=540, height=650,
    legend=dict(
    orientation="h",
    yanchor="bottom",
    y=-0.4,
    xanchor="right",
    x=1))
c1.markdown("<h4 style = 'text-align:center;color:gray;'>% DE TIPOS DE CALENDARIOS</h4>", unsafe_allow_html=True)
c1.plotly_chart(fig)

ft=df.groupby(['DEPORTE'])[['FECHA']].count().sort_values('FECHA', ascending = False).reset_index()
ft=ft.rename(columns={'FECHA':'PARTICIPACIONES'})
ft=ft.head(10)



# crear gráfica
fig = px.bar(ft, x='DEPORTE', y='PARTICIPACIONES',color='DEPORTE',color_discrete_map={'GOLF':'silver','TENIS':'lime','AUTOMOVILISMO':'red','PATINAJE':'magenta','ECUESTRE':'saddlebrown','GIMNASIA':'gold','LUCHA':'orangered','TIRO DEPORTIVO':'lightslategray','ACTIVIDADES SUBACUATICAS':'navy','JUDO':'white'})

# agregar detalles a la gráfica
fig.update_layout(
    xaxis_title = 'DEPORTE',
    yaxis_title = 'PARTICIPACIONES',
    
    template = 'simple_white',
    title_x = 0.5, 
    width=650, height=600,
    paper_bgcolor='rgba(0,0,0,0)',
    plot_bgcolor='rgba(0,0,0,0)')
fig.update_layout(showlegend=False)               
c2.markdown("<h4 style = 'text-align:center;color:gray;'>DEPORTES QUE PROGRAMAN MAS FECHAS</h4>", unsafe_allow_html=True)
c2.plotly_chart(fig)



#--------------------------------------------------------------------------------------------------------------------------



